### ISSUE TITLE
duckdb connection failed due to lib error

### ISSUE THREAD

**Issue by rightx2** [MotherDuck-Open-Source/metabase_duckdb_driver#36]
**Describe the bug**
When connecting duckdb database, got an error:

```
/tmp/libduckdb_java6675790097643844395.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/libduckdb_java6675790097643844395.so)
```

**To Reproduce**
- duckdb file version
```
D PRAGMA version
  ;
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v1.1.3          │ 19864453f7 │
└─────────────────┴────────────┘

```

- metabase docker-compose:
```
  metabase:
    image: metabase/metabase:v0.52.9.2
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - $HOME/Programming/Workspace/chois_duckdb:/metabase-data
      - ./metabase_plugins/duckdb.metabase-driver.jar:/plugins/duckdb.metabase-driver.jar
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres-metabase
      MB_PLUGINS_DIR: /plugins
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres-metabase:
    image: postgres:17
    container_name: postgres-metabase
    hostname: postgres-metabase
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-metabase-volume3:/var/lib/postgresql/data
```
- duckdb.metabase-driver.jar version
```
https://github.com/motherduckdb/metabase_duckdb_driver/releases/tag/0.2.12-b
```
 

**Expected behavior**
duckdb connection succeeded

**Screenshots**

![Image](https://github.com/user-attachments/assets/267dedf4-0193-472e-be0a-bd64a8032f8b)

**Environment**
 - OS/Platform: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

 - Metabase version:
metabase/metabase:v0.52.9.2 (Docker)

 - Metabsae DuckDB driver version: 1.1.3 (https://github.com/motherduckdb/metabase_duckdb_driver/releases/tag/0.2.12-b)

**Additional context**
